### ISSUE TITLE
Not compatible with Rails 7

### ISSUE THREAD

**Issue by testwisely** [Mange/roadie-rails#103]
roadie-rails (~> 2.2) was resolved to 2.2.0, which depends on
      railties (>= 5.1, < 6.2)

**Comment by maxwell** [comment]
I think we just need a new version cut with the relaxed requirements

until then, you can  use

```ruby
gem 'roadie-rails', git:'https://github.com/Mange/roadie-rails.git'
```

**Comment by Mange** [comment]
I'm in the process of releasing a new version. Waiting for the CI to finish the build. :smile:

**Comment by Mange** [comment]
Version 2.3.0 was just pushed with a fix for this.
