### ISSUE TITLE
Implement Roadie as an ActionMailer interceptor?

### ISSUE THREAD

**Issue by tomasc** [Mange/roadie-rails#35]
Would not the use of [ActionMailer interceptors](http://guides.rubyonrails.org/action_mailer_basics.html#intercepting-emails) provide more clean implementation of Roadie in Rails?

**Comment by Mange** [comment]
Oh, I forgot to respond to this specific issue. I responded in the comment thread on #15.

Here's my reply from that thread:

> Because you cannot selectively activate it in specific mailers.
> Interceptors are global.

To expand on this: This also removes the ability to have customized configuration per mailer. When the global handler is executed, we lose all context and scoping, so I cannot even tell who generated the email.
