### ISSUE TITLE
Roadie is unable to located assets with Rails 4.2.1

### ISSUE THREAD

**Issue by sujoyg** [Mange/roadie-rails#41]
I upgraded rails to 4.2.1 and roadie-rails to 3.0.5. After that, with no code change, sending emails started to fail with something like unable to find to the following file:
`/assets/application-00acbfe0213dff8c5ba7232e3dabb3584c9e216bdb489f69d7aa20e0e101f3e6.css`

It turns out that the problem is that rails upgraded sprockets to version 3 from version 2. Roadie 3.0.5 will not work with sprockets 3.

The solution was to manually downgrade sprockets back to version 2.

**Comment by Mange** [comment]
I just released *version 1.0.6* with a fix for this issue. Thank you for reporting it!
