### ISSUE TITLE
Previewing section of README not working

### ISSUE THREAD

**Issue by davekaro** [Mange/roadie-rails#43]
I had to change the previewing section (https://github.com/Mange/roadie-rails#previewing) code to make `html` output work.

From

`format.html { render html: email.html_part.decoded }`

to

`format.html { render html: email.html_part.decoded.html_safe }`

This makes sense to me, but was surprised nobody else ran into it. Is it possible I've got something configured wrong? Does the `decoded` method return an `html_safe` string sometimes?

**Comment by Mange** [comment]
No that is most likely correct. I wrote the snippet from memory as I no
longer worked with Rails when I typed it out.

Thanks for reporting it. I'll update the README.

ons 24 jun 2015 18:52 Dave Kroondyk <notifications@github.com> skrev:
