### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by ckirk** [Mange/roadie-rails#44]
I'm struggling to get roadie-rails to links to absolute paths. I believe it has something to do with my configuration. Not sure if its a ENV config issue or a roadie-rails config issue...

Are all the roadie configuration options supported by roadie-rails? I'm using a data-roadie-ignore tag in a <script> tag and it is still being moved inline. I would like to keep my @media queries in a <script> tag in the head of my emails. Thanks in advance for any help!

-Chris

**Comment by Mange** [comment]
> Are all the roadie configuration options supported by roadie-rails?

Yes.

> I'm using a data-roadie-ignore tag in a [sic]

In a what?

I'm going to need you to explain your current situation more for me to be able to help you. :-)
