### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by sgringwe** [Mange/roadie-rails#49]
The gemspec currently specifies < 4.3 rails version. The rails 5 beta1 was just released. Is there plans to update to support rails 5?

**Comment by Mange** [comment]
Yes, most certainly. A beta is a pretty good point to work from.

Pull Requests are welcome until I get going myself, which is going to take
some time due to the holidays.

lör 19 dec. 2015 05:08 Scott Ringwelski <notifications@github.com> skrev:

**Comment by sgringwe** [comment]
@Mange PR attached
