### ISSUE TITLE
Unable to load mail.css with rails 4.2.6, roadie-rails 1.1.1

### ISSUE THREAD

**Issue by Hugo-Hache** [Mange/roadie-rails#56]
When setting Rails.application.assets.compile = false (prod env), Roadie has only one asset provider: 
`#<Roadie::FilesystemProvider app/public>`

In #46, AssetPipelineProvider creation is done in a block given to `Rails.application.config.assets.configure`, normally _invoked with environment when the environment is initialized_ (cf. [sprocket-rails README](https://github.com/rails/sprockets-rails)). 

However, this block is never called, and then without AssetPipelineProvider Roadie is unabled to find my precompiled mail.css suffixed with the digest. 

Did I misconfigure Rails or is this a bug ? Thanks !

**Comment by Mange** [comment]
I'm not sure I understand completely, so please bear with me where I try to understand.

You're not compiling on `production`. Do you precompile or do you work with static assets that need no compilation?

When you include the asset in your email, do you use the built-in asset helpers (`stylesheet_link_tag`)? Does it output the asset as `/assets/stylesheets/mail-<sha>.css` or as `/assets/stylesheets/mail.css`?

**Comment by Hugo-Hache** [comment]
Issue appeared only in production where I use asset precompilation.
Thanks to your precise questions I spotted that I was mistakenly not using `stylesheet_link_tag`, but a direct link. Sorry bothering you, and thanks for the blazing fast and effective answer @Mange !

**Comment by Mange** [comment]
I'm glad it worked out for you! ☺️

Den ons 16 mars 2016 15:25Hugo Hache <notifications@github.com> skrev:
