### ISSUE TITLE
Why not use config.action_mailer.default_url_options as defaults for config.roadie.url_options?

### ISSUE THREAD

**Issue by koenpunt** [Mange/roadie-rails#57]
I've configured roadie like this:

``` rb
config.roadie.url_options = config.action_mailer.default_url_options
```

Which seems sensible enough to be the default IMO.

What do you think?

**Comment by Mange** [comment]
If you've configured it, then all links in your email would be absolute and
you wouldn't need to configure it for Roadie AFAIK. Am I missing something?

Den fre 18 mars 2016 14:49Koen Punt <notifications@github.com> skrev:

**Comment by koenpunt** [comment]
The `default_url_options` are not used for assets, only for links, so image paths are still untouched.

**Comment by koenpunt** [comment]
That being said, having those as default for assets wouldn't be desired, but for links it would be

**Comment by Mange** [comment]
Yeah, in the context of Rails you can handle both from the framework out of
the box (default_url_options and asset_host), so path rewriting isn't the
biggest feature in the context of Rails.

Den lör 19 mars 2016 17:35Koen Punt <notifications@github.com> skrev:

**Comment by koenpunt** [comment]
But I believe `asset_host` isn't supported?

**Comment by Mange** [comment]
It's not fully automatic no, but it's possible to get it to work using a
URL rewriting provider for your assets.

One could also opt for writing the styles inside the email and there should
also be no problem with the asset host.

Den sön 20 mars 2016 12:06Koen Punt <notifications@github.com> skrev:
