### ISSUE TITLE
Roadie: Cannot inline "html" from <path> stylesheet. If this is valid CSS, please report a bug.

### ISSUE THREAD

**Issue by jbernardo95** [Mange/roadie-rails#58]
```
Roadie: Cannot inline "html" from <path> stylesheet. If this is valid CSS, please report a bug.
```

I am getting this error in production, the css is generated by the rails asset pipeline, do you have any idea why this is happening ?

**Comment by rossgeesman** [comment]
I am seeing the same error. Any idea of how one might fix it?

**Comment by Mange** [comment]
What styles do you have for the <html> element? Do you have an <html> element in your email?

**Comment by Mange** [comment]
On mobile, cannot access backticks and GitHub filtered out the [html] tags.

**Comment by jbernardo95** [comment]
@Mange I should I have closed this long ago, at the time I had a workaround to fix this.

Can not remember what it was.

**Comment by rsl** [comment]
man i wish the fix for this was documented here. just hit same issue. cannot remove the html and body selector rules from this css.
