### ISSUE TITLE
WARN: Errno::ENOENT: No such file or directory - getcwd

### ISSUE THREAD

**Issue by twetzel** [Mange/roadie-rails#62]
hey guys got this Error today .. appeared when sending emails via sidekiq (plus sidekiq-unique-jobs)

full-log:
WARN: Errno::ENOENT: No such file or directory - getcwd
2016-05-31T14:59:11.317Z 16365 TID-1374vo WARN: /home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-3.1.1/lib/roadie/filesystem_provider.rb:13:in `pwd'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-3.1.1/lib/roadie/filesystem_provider.rb:13:in `initialize'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-3.1.1/lib/roadie/document.rb:34:in `new'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-3.1.1/lib/roadie/document.rb:34:in `initialize'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-rails-1.1.1/lib/roadie/rails/document_builder.rb:5:in `new'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-rails-1.1.1/lib/roadie/rails/document_builder.rb:5:in `build'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-rails-1.1.1/lib/roadie/rails/mail_inliner.rb:29:in `transform_html'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-rails-1.1.1/lib/roadie/rails/mail_inliner.rb:21:in `improve_body'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-rails-1.1.1/lib/roadie/rails/mail_inliner.rb:13:in `execute'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-rails-1.1.1/lib/roadie/rails/inline_on_delivery.rb:23:in `inline_styles'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/roadie-rails-1.1.1/lib/roadie/rails/inline_on_delivery.rb:10:in `deliver'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/actionmailer-4.2.5/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/devise-3.5.6/lib/devise/models/authenticatable.rb:170:in `send_devise_notification'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/devise_invitable-1.5.5/lib/devise_invitable/model.rb:170:in `deliver_invitation'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/devise_invitable-1.5.5/lib/devise_invitable/model.rb:134:in `invite!'
/home/smuncher/smunch-production/releases/20160530105259/app/workers/dish_choose_worker.rb:55:in `block (2 levels) in perform'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:46:in `each'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:46:in `each'
/home/smuncher/smunch-production/releases/20160530105259/app/workers/dish_choose_worker.rb:21:in `block in perform'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:46:in `each'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:46:in `each'
/home/smuncher/smunch-production/releases/20160530105259/app/workers/dish_choose_worker.rb:15:in `perform'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:152:in `execute_job'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/rollbar-2.11.3/lib/rollbar/plugins/sidekiq/plugin.rb:9:in `call'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/logging.rb:32:in `with_context'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `call'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:129:in `block in process'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:168:in `stats'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:128:in `process'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:80:in `process_one'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:68:in `run'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:17:in `watchdog'
/home/smuncher/smunch-production/shared/bundle/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:25:in `block in safe_thread'

**Comment by Mange** [comment]
The directory that is the worker's working directory (what a tongue
twister...) no longer exists. I suspect it's a worker that was started a
while ago and now that release directory has been cleaned up by Capistrano
because you've deployed a number of new versions since then.

Maybe it never stopped successfuly on some deploy?

Does this happen if you forcefully restart all your workers? (Make sure no
one is still running before starting the new ones)

Den tis 31 maj 2016 17:12Torsten Wetzel <notifications@github.com> skrev:

**Comment by twetzel** [comment]
thanks a lot .. works like charm again!
I think something crazy happened (got also errors in rails) it seems as server bash was broken .. I could imagine the server was overloaded or in maintenance by the hoster, because everything was fine after next deployment.

So not roadie related!

thanks again for your time .. and sorry for bother you with that nonsense (just didn`t know what happened)

**Comment by Mange** [comment]
No problem. I'm glad it worked out for you.

Den tis 31 maj 2016 21:13Torsten Wetzel <notifications@github.com> skrev:
