### ISSUE TITLE
URLs shown for hrefs

### ISSUE THREAD

**Issue by malagant** [Mange/roadie-rails#77]
I use roadie and rails and in my generated emails I see urls printed everywhere (Links etc.)
Is this a feature? I couldn't find any documentation here.
E.g.: When I have  <%= link_to image_tag ('frontend/facebook.svg), store.facebook_url />
The output adds the link to the right of the SVG.

**Comment by Mange** [comment]
That looks very strange to me. Would you mind posting a full example and
the resulting HTML?

This could be an email client feature that has little to do with the
resulting HTML, or that the link gets extra spaces inside it which shows up
unless hidden with CSS.

mån 23 okt. 2017 kl 15:10 skrev Michael Johann <notifications@github.com>:

**Comment by malagant** [comment]
Thank you for your quick support. I found out that the gem rails_email_preview did the change, wenn using roadie for email preview.
Closing this. Thanks again. 👍
