### ISSUE TITLE
Does not inline styles in Rails 5.x

### ISSUE THREAD

**Issue by JohnSmall** [Mange/roadie-rails#78]
Working on a Rails 5 project using 

     include Roadie::Rails::Automatic
   
 in the mailer

and in the code

     SomeEmailer(params).deliver_now

Roadie Rails does not inline the styles. Checking the code I see it is still using #deliver, which is deprecated in Rails 4.x and removed in Rails 5.x in preference for deliver_now, or deliver_later

If I switch to using 

     include Roadie::Rails::Mailer

and in my code

     roadie_mail &etc

Then it should inline the styles immediately. But it doesn't. If I check the email_preview, the head content is still present, and the styles have not been put inline.

I see others are using Rails 5. What is the trick to getting Roadie to work in Rails 5?

**Comment by JohnSmall** [comment]
Ahh! I've worked it out.

I had a default asset host set up for my mailer. Which meant Roadie couldn't find the css files to inline from. 

I think a minor update to the instructions could make that point clearer. If you moved the paragraph "Roadie will not be able to find your stylesheets..." to immediately after the paragraph "Use normal stylesheet_link_tag and foo_path methods.." then it makes it clearer that you can use normal stylesheet_link_tag methods IF AND ONLY IF you haven't set asset_host on your mailer.

The in addition you need to make it clear that 

     config.roadie.url_options = {host: "my-app.com", scheme: "https"}

Is not optional, it's required, and reiterate that point immediately after the warning not to use asset_host. That way all the configuration concepts are in the one place.

1. You can use stylesheet_link_tag as normal
2. But you must not set asset_host on your mailer
3. And because you've not set asset_host you must set config.roadie.url_options.

Once all those things are in place it works.

But the #deliver method still needs updating for Rails 5.

**Comment by Mange** [comment]
Sounds reasonable. PRs are welcome.
