### ISSUE TITLE
data-roadie-ignore causing file not to load at all.

### ISSUE THREAD

**Issue by petran** [Mange/roadie-rails#79]
When I use Internal css data-roadie-ignore works fine.

<style type="text/css" data-roadie-ignore>
  @media screen and (max-width: 480px) {
    body {
      background-color: #ebedf1;
    }
  }
</style>

This works just fine, when I am trying to ignore a css file from my haml file
  
  = stylesheet_link_tag 'email-mobile', :'data-roadie-ignore' => true 

This doesn't work as it expected. the css file is not been loaded at all.

**Comment by Mange** [comment]
What is the expected behavior in your case? The file is ignored by you so I would expect it to not be loaded.

That a plain style element is not ignored properly does sound like a bug however.

Am I misunderstanding you? ☺️

**Comment by petran** [comment]
You are right, you can close this issue.

**Comment by Mange** [comment]
I'm glad it worked out. :-)
