### ISSUE TITLE
any options to prevent email templates from clipped messages in gmail?

### ISSUE THREAD

**Issue by jaswinder97** [Mange/roadie-rails#91]
It seems like incase it loads assets pipeline with all images, icons, long spaces etc. the email templates clipped while viewing in gmail

**Comment by Mange** [comment]
I think your best bet is to reduce the number of styles you apply on your document. I think the clipping happens after a certain number of bytes.

Use an email-specific stylesheet if you get a lot of things applied, don't use reset frameworks and don't try to make the design pixel-perfect so 8bly change what's important (like color, but not like spacing, etc.)
