### ISSUE TITLE
Possible to allow for Rails 7 alpha?

### ISSUE THREAD

**Issue by floydj** [Mange/roadie-rails#94]
I'd like to use edge rails, which is 7.0.0.alpha. But roadie prevents this with the gem spec:

```
 spec.add_dependency "railties", ">= 5.1", "< 6.2"
```

Any chance of getting that updated?

**Comment by Mange** [comment]
You could fork the gem and test it with that version. Please report back your results.

If it seems to work well, we could add official support for it.
